#!/usr/bin/env python3
"""Gold-corpus attribution audit — READ-ONLY (P67.9 T3.4, pulled forward).

Flags cross-speech verbatim / near-verbatim duplicate claims (the
Mora/Rivera class: one guest's story or one stock line appearing in both
speeches' corpora, which can leak verdicts across speeches in eval). Scans:

* the 277-claim gold corpus (``claim_set.jsonl`` = train + heldout), and
* the 289 published claims (``site-pca/data/claims.json``),

comparing only across DIFFERENT speeches. Report-only: no gold file is
ever written.

I6 discipline: heldout rows are loaded through ``_texts_only`` which keeps
``sid/speech/text`` and immediately discards every other field — labels,
rationales, and claim types are never materialized, so this audit cannot
burn the read-once heldout budget.

Method: exact duplicates on normalized text (lowercase, punctuation and
whitespace collapsed), plus near-verbatim pairs by Jaccard similarity over
word 4-gram shingles (>= 0.6). Short sentences (< 6 words) are skipped —
applause lines ("Thank you.") duplicate trivially and carry no attribution
risk.

Usage (repo root):
  PYTHONPATH=. .venv/bin/python scripts/attribution_audit.py \
      [--out metrics/attribution_audit.json] [--threshold 0.6]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from itertools import combinations
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

GOLD = REPO / "eval" / "benchmarks" / "claim-set" / "claim_set.jsonl"
PUBLISHED = REPO / "site-pca" / "data" / "claims.json"

_WORD_RX = re.compile(r"[a-z0-9]+")


def _texts_only(row: dict, sid_key: str, speech_key: str, text_key: str) -> dict:
    """Keep identification + text ONLY — labels/rationales are never held."""
    return {"sid": str(row.get(sid_key) or ""),
            "speech": str(row.get(speech_key) or ""),
            "text": str(row.get(text_key) or "")}


def _norm_words(text: str) -> list[str]:
    return _WORD_RX.findall(text.lower())


def _shingles(words: list[str], n: int = 4) -> set[tuple[str, ...]]:
    if len(words) < n:
        return {tuple(words)} if words else set()
    return {tuple(words[i:i + n]) for i in range(len(words) - n + 1)}


def _jaccard(a: set, b: set) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def audit(rows: list[dict], threshold: float, min_words: int = 6) -> dict:
    usable = []
    for r in rows:
        words = _norm_words(r["text"])
        if len(words) < min_words:
            continue
        usable.append({**r, "_words": words,
                       "_norm": " ".join(words),
                       "_sh": _shingles(words)})
    exact: list[dict] = []
    near: list[dict] = []
    by_norm: dict[str, list[dict]] = {}
    for r in usable:
        by_norm.setdefault(r["_norm"], []).append(r)
    for norm, group in by_norm.items():
        speeches = {g["speech"] for g in group}
        if len(speeches) > 1:
            exact.append({"text": group[0]["text"],
                          "sids": sorted(g["sid"] for g in group)})
    exact_sids = {s for e in exact for s in e["sids"]}
    for a, b in combinations(usable, 2):
        if a["speech"] == b["speech"]:
            continue
        if a["sid"] in exact_sids and b["sid"] in exact_sids:
            continue
        sim = _jaccard(a["_sh"], b["_sh"])
        if sim >= threshold:
            near.append({"similarity": round(sim, 3),
                         "a": {"sid": a["sid"], "text": a["text"]},
                         "b": {"sid": b["sid"], "text": b["text"]}})
    near.sort(key=lambda x: -x["similarity"])
    return {"n_compared": len(usable), "exact_cross_speech": exact,
            "near_verbatim_cross_speech": near}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default="metrics/attribution_audit.json")
    ap.add_argument("--threshold", type=float, default=0.6)
    args = ap.parse_args()

    gold_rows = [_texts_only(json.loads(l), "sid", "speech", "text")
                 for l in GOLD.read_text(encoding="utf-8").splitlines() if l.strip()]
    pub = json.loads(PUBLISHED.read_text(encoding="utf-8"))
    reports = {r["id"]: r.get("speaker", r["id"]) for r in json.loads(
        (REPO / "site-pca" / "data" / "reports.json").read_text())}
    pub_rows = [{"sid": c.get("id", ""),
                 "speech": reports.get(c.get("report_id"), c.get("report_id", "")),
                 "text": c.get("claim_text", "")}
                for c in pub]

    result = {
        "date": "generated by scripts/attribution_audit.py — see git log",
        "gold_corpus": audit(gold_rows, args.threshold),
        "published_claims": audit(pub_rows, args.threshold),
        "params": {"threshold": args.threshold, "shingle_n": 4, "min_words": 6},
        "i6_note": "heldout rows loaded texts-only; labels never materialized",
    }
    for name in ("gold_corpus", "published_claims"):
        r = result[name]
        print(f"{name}: {r['n_compared']} claims compared — "
              f"{len(r['exact_cross_speech'])} exact cross-speech dups, "
              f"{len(r['near_verbatim_cross_speech'])} near-verbatim pairs")
        for e in r["exact_cross_speech"][:5]:
            print(f"  = {e['sids']}: {e['text'][:90]}")
        for n in r["near_verbatim_cross_speech"][:5]:
            print(f"  ~ {n['similarity']} {n['a']['sid']} ↔ {n['b']['sid']}: "
                  f"{n['a']['text'][:80]}")
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2, ensure_ascii=False))
    print(f"written: {out}")


if __name__ == "__main__":
    main()
