"""
HTML report generator with live-update support via SSE.

Generates a standalone HTML report for each fact-check run.
The report includes:
  - Header: speaker, date, venue
  - Summary: verdict counts with visual bar
  - Per-claim verdicts with evidence links
  - SSE endpoint for live updates during long pipeline runs

This module is a stub — HTML generation is implemented; SSE requires
a running web server (FastAPI).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from truthbot.models import Report

logger = logging.getLogger(__name__)

_VERDICT_COLORS = {
    "True": "#2e7d32",
    "Mostly True": "#558b2f",
    "Misleading": "#f57c00",
    "Exaggerated": "#ef6c00",
    "False": "#c62828",
    "Unverifiable": "#546e7a",
}

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:title" content="Fact Check: {speaker}">
  <meta property="og:description" content="{og_description}">
  <meta property="og:type" content="article">
  {og_image_tag}
  <title>Fact Check: {speaker} — truth-bot</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #222; }}
    h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
    .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 2rem; }}
    .summary {{ display: flex; gap: 0.75rem; flex-wrap: wrap; margin-bottom: 2rem; }}
    .badge {{ padding: 0.3rem 0.8rem; border-radius: 2rem; color: white; font-weight: 600; font-size: 0.85rem; }}
    .claim {{ border-left: 4px solid #ddd; padding: 1rem 1.25rem; margin-bottom: 1.5rem; background: #f9f9f9; }}
    .claim-text {{ font-weight: 600; margin-bottom: 0.5rem; }}
    .verdict-label {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 0.25rem; color: white; font-size: 0.8rem; font-weight: 700; margin-bottom: 0.4rem; }}
    .explanation {{ font-size: 0.9rem; color: #444; margin-bottom: 0.5rem; }}
    .confidence {{ font-size: 0.8rem; color: #888; }}
    footer {{ margin-top: 3rem; font-size: 0.8rem; color: #aaa; border-top: 1px solid #eee; padding-top: 1rem; }}
  </style>
</head>
<body>
  <h1>Fact Check: {speaker}</h1>
  <div class="meta">{date_str}{venue_str}</div>

  <div class="summary">
    {badges}
  </div>

  <section id="claims">
    {claims_html}
  </section>

  <footer>Generated by <a href="https://github.com/jackiemclean/truth-bot">truth-bot</a> · {created_at}</footer>
</body>
</html>
"""


class WebPublisher:
    """
    Generate standalone HTML fact-check reports.

    Parameters
    ----------
    output_dir:
        Directory where HTML files are written.
    base_url:
        Base URL for report links (used in OG tags and RSS).
    """

    def __init__(
        self,
        output_dir: Optional[str | Path] = None,
        base_url: str = "https://example.com",
    ) -> None:
        self._output_dir = Path(output_dir) if output_dir else None
        self.base_url = base_url

    def generate_html(self, report: Report) -> str:
        """
        Render a complete HTML report for a fact-check run.

        Parameters
        ----------
        report:
            The completed Report to render.

        Returns
        -------
        str
            HTML string.
        """
        speaker = report.transcript.speaker
        date_str = (
            report.transcript.date.strftime("%B %d, %Y")
            if report.transcript.date
            else ""
        )
        venue_str = f" · {report.transcript.venue}" if report.transcript.venue else ""

        # Summary badges
        summary = report.verdict_summary
        badges = " ".join(
            f'<span class="badge" style="background:{_VERDICT_COLORS.get(label, "#999")}">'
            f'{count} {label}</span>'
            for label, count in summary.items()
            if count > 0
        )

        # Claims + verdicts
        claims_html_parts = []
        for claim in report.claims:
            verdict = report.verdict_for(claim.id)
            if not verdict:
                continue
            color = _VERDICT_COLORS.get(verdict.label.value, "#999")
            part = (
                f'<div class="claim">'
                f'<div class="claim-text">{self._escape(claim.text)}</div>'
                f'<span class="verdict-label" style="background:{color}">{verdict.label.value}</span>'
                f'<div class="explanation">{self._escape(verdict.explanation)}</div>'
                f'<div class="confidence">Confidence: {verdict.confidence.value}</div>'
                f'</div>'
            )
            claims_html_parts.append(part)

        og_desc = f"{report.checkable_claims} claims checked · " + ", ".join(
            f"{v} {l}" for l, v in summary.items() if v > 0
        )
        og_image_tag = (
            f'<meta property="og:image" content="{self.base_url}/reports/{report.id}/card.png">'
        )

        html = _HTML_TEMPLATE.format(
            speaker=self._escape(speaker),
            date_str=date_str,
            venue_str=venue_str,
            badges=badges,
            claims_html="\n".join(claims_html_parts),
            og_description=og_desc,
            og_image_tag=og_image_tag,
            created_at=report.created_at.strftime("%Y-%m-%d %H:%M UTC"),
        )
        return html

    def write_report(self, report: Report) -> Path:
        """
        Generate and write the HTML report to disk.

        Parameters
        ----------
        report:
            The report to render.

        Returns
        -------
        Path
            Path to the written HTML file.
        """
        if self._output_dir is None:
            from truthbot.config import settings
            self._output_dir = settings.report_dir

        self._output_dir.mkdir(parents=True, exist_ok=True)
        path = self._output_dir / f"{report.id}.html"
        html = self.generate_html(report)
        path.write_text(html, encoding="utf-8")
        logger.info("HTML report written to %s", path)
        return path

    def sse_event(self, event_type: str, data: dict) -> str:
        """
        Format a Server-Sent Events message.

        Used by the FastAPI SSE endpoint to push live progress updates.

        Parameters
        ----------
        event_type:
            SSE event name (e.g. "claim_verified", "pipeline_complete").
        data:
            JSON-serializable data payload.

        Returns
        -------
        str
            SSE-formatted string: "event: X\\ndata: {...}\\n\\n"
        """
        import json
        return f"event: {event_type}\ndata: {json.dumps(data)}\n\n"

    @staticmethod
    def _escape(text: str) -> str:
        """HTML-escape a string."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
